name: SCP Feed Generator

on: push

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedgenerator requests beautifulsoup4

      - name: Run script
        run: python scp_rss.py

      - name: Copy files to folders
        run: |
          for file in scp_s*.xml; do
            season_num=$(echo "$file" | cut -d '_' -f 2)
            mkdir -p "feeds/Season$season_num"
            mv "$file" "feeds/Season$season_num/"
          done

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update SCP RSS feeds [skip ci]"
          git push "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master
